# Use a C development environment as the parent image
FROM gcc:latest

# Set the working directory to /app
WORKDIR /app

# Copy the source code to the container
COPY . .

# Build the project
RUN gcc -o webserver -static webserver.c

# Set the command to run the executable
CMD ["./webserver"]
