# Use the official Golang image as the base image
FROM golang:alpine as build

# Set the working directory to /app
WORKDIR /app

# Copy the source code to the working directory
COPY main.go .

# Build the Go application statically
RUN go build -o app -ldflags '-extldflags "-static"' main.go

# Use the Alpine image as the base image
FROM alpine:latest

# Copy the binary from the first stage
COPY --from=build /app/app /app/app

# Expose port 8080 for the HTTP server
EXPOSE 8080

# Set the entry point for the container
ENTRYPOINT ["/app/app"]